### PR TITLE
UI tests: wrap more webdriver functions to retry_if_known_issue

### PR DESCRIPTION
**Pull request by ljelinkova**

### CODE REVIEW

**Comment by tinez** [comment]
I admit - I don't precisely track all the selenium failures and I'm not exactly sure which calls are prone to those timeout exceptions, but this is a lot of stuff wrapped. Are we sure we want all of this in retries?

**Comment by ljelinkova** [comment]
I think we do. It takes much more time to investigate failed job then to retry a method while the job is running. Let's admin, Selenium is not super reliable and wrapping it helps a lot.

**Pull request merged**
