### PR TITLE
el9: Skip test broken by libvirt regression

### PR DESCRIPTION
**Pull request by tinez**
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

### CODE REVIEW

**Review by michalskrivanek — APPROVED** [review]
yeah, I think test_next_run_unplug_cpu takes care of the actually-unplugged nic by restarting the vm so this indeed should work

**Comment by tinez** [comment]
The other test uses that NIC most probably, let's try with 2 of them disabled

**Comment by tinez** [comment]
Works. Unfortunately we cannot use `strict` that would fail the test once the issue is fixed. Let's post a revert PR and check on this in a week.

**Pull request merged**
