### PR TITLE
Revert OVN workaround for backwards compatibility on minor versions

### PR DESCRIPTION
**Pull request by erav**

### CODE REVIEW

**Comment by erav** [comment]
rhvh machine has ` ovn-2021-21.12.0-46.el8fdp.x86_64 `
engine machine has ` ovn-2021-21.12.0-69.el8fdp.x86_64 `

but ost still fails with rhvh/var/log/ovn/ovn-controller.log:
```
2022-06-02T08:29:21.149Z|00028|lflow|WARN|error parsing match "ct.est && ct_mark.blocked == 0": Syntax error at `ct_mark.blocked' expecting field name.
2022-06-02T08:29:21.149Z|00029|lflow|WARN|error parsing actions "ct_commit { ct_mark.blocked = 1; }; /* drop */": Syntax error at `ct_mark.blocked' expecting field name.
```

**Comment by erav** [comment]
latest runs passed where engine machine has ` ovn-2021-21.12.0-73.el8fdp.x86_64 ` and rhvh machine has ` ovn-2021-21.12.0-46.el8fdp.x86_64 `
so looks ok to merge

**Review by tinez — APPROVED** [review]

**Pull request merged**
