### PR TITLE
tr: skip terraform tests and run go-ovirt-client instead

### PR DESCRIPTION
**Pull request by michalskrivanek**
go-ovirt-client tests are working (unlike terraform ATM), so let's run
them!

### CODE REVIEW

**Review by janosdebugs — APPROVED** [review]
LGTM

**Comment by michalskrivanek** [comment]
passing is silent right now.
when tests fail we actually do get a nice output, stdout(or err?) gets dumped into OST's console

**Comment by janosdebugs** [comment]
Thanks @michalskrivanek

**Pull request merged**
