### PR TITLE
temporary fix to speed up node

### PR DESCRIPTION
**Pull request by tinez**
Should be removed once we have it in ost-images.

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

### CODE REVIEW

**Comment by michalskrivanek** [comment]
maybe https://github.com/oVirt/ost-images/pull/47 is easy enough. let's see if it works

**Comment by didib** [comment]
Maybe https://github.com/oVirt/ovirt-node-ng/pull/13 ?

**Comment by tinez** [comment]
https://github.com/oVirt/ovirt-node-ng/pull/13 has been merged, not needed anymore

**Pull request closed without merging**
