### PR TITLE
chrony: Use single server instead of pool

### PR DESCRIPTION
**Pull request by acernek**
Let's make openscap report happy.

### CODE REVIEW

**Comment by michalskrivanek** [comment]
lgtm, does it work?

**Comment by acernek** [comment]
It does fix the openscap fail, but I'm a little bit worried it might lead to bigger time differences between hosts (this way it chooses one server from the pool at random) - unfortunately I will probably not have a time to check the time differences until next week. @tinez

**Comment by michalskrivanek** [comment]
why not adding a new server line with bogus ip/name?

**Comment by acernek** [comment]
If I read it correctly, the openscap test also checks for pools (and fails if it finds one), so I think we have to replace it.

**Comment by michalskrivanek** [comment]
I don't think we should go ahead with this. I prefer to keep DHCP-pushed configuration than losing time sync. In loaded environment the time soon goes off without proper NTP.

I think it's perfectly ok to ignore rules that do not have remediation and need to be manually resolved.

**Pull request closed without merging**
