### PR TITLE
selenium: fix grafana changes on el9stream

### PR DESCRIPTION
**Pull request by michalskrivanek**
el9strema Grafana changed the case of Test to test, it's enough to match
just the "Save & " part, that works on both el8 and el9

### CODE REVIEW

**Review by tinez — APPROVED** [review]

**Comment by tinez** [comment]
Still failing on el9stream

**Comment by michalskrivanek** [comment]
error checks still need to be reimplemented

**Comment by michalskrivanek** [comment]
tested on el8stream and el9stream

**Pull request merged**
