### PR TITLE
requirements.txt: use specific openstacksdk commit 

### PR DESCRIPTION
**Pull request by erav**
Openstacksdk>=0.62.0 is now published on pypi. Use it going forward.

Change-Id: I26a094b522202ace8c5e0d30749571a46d5d25d9
Signed-off-by: Eitan Raviv <eraviv@redhat.com>

### CODE REVIEW

**Comment by almusil** [comment]
I don't think that this will work. The message states `<=0.98.999` latest release is `0.103.0` and the comments says that we need `>=0.62.0`, closest to that is `0.99.0` which is out of range already. So I guess we will need to pin to some commit in openstacksdk before `0.99.0` release or use newer openstack ansible that is compatible with those newer versions (this step would probably require rewrite of the used roles).

**Comment by mwperina** [comment]
Isn't there the correct packaged RPM we can use?

**Comment by erav** [comment]
> Isn't there the correct packaged RPM we can use?

that's what i thought would happen automatically when I changed to `openstacksdk`. So Ales, do we have an el8s vs. openstack-ansible compatibility issue?

**Comment by almusil** [comment]
I don't think there is a rpm, openstack did only release of `0.99.0` after `0.61.0`. It's not about el8 or el9 this is taken from pip.

**Comment by erav** [comment]
> I don't think there is a rpm, openstack did only release of `0.99.0` after `0.61.0`. It's not about el8 or el9 this is taken from pip.

and where is the version of openstack-ansible decided? by the os version of ansible? if so, pinning to a pre-0.99 might break el9?

**Comment by almusil** [comment]
That's decided by the version installed, pinning doesn't help because only version available before `0.99.0` is `0.61.0` which would break the tests.

**Comment by almusil** [comment]
another solution might be to pin specific commit from openstacksdk (not sure if it's possible with pip). We need [0], so pinning that one should work without breaking anything else.

[0] https://github.com/openstack/openstacksdk/commit/44c551560242379daa3ae3571aa260f7c6858cb7

**Comment by erav** [comment]
ok I'll try

**Review by almusil — APPROVED** [review]

**Comment by michalskrivanek** [comment]
good enough

**Pull request merged**
