### PR TITLE
basic: Test zero-copy migration policy

### PR DESCRIPTION
**Pull request by mz-pdm**

### CODE REVIEW

**Comment by mz-pdm** [comment]
@michalskrivanek, any idea why it fails on rhel8 with

```
<testcase classname="basic-suite-master.test-scenarios.test_002_bootstrap" name="test_generate_openscap_report" time="82.722">

      <failure message="ost_utils.ansible.module_mappers.AnsibleExecutionError: Error running ansible: rc=2, stdout=ost-basic-suite-master-host-1
```

I cannot find any details about the error and it looks unrelated to the patch.

**Comment by michalskrivanek** [comment]
> @michalskrivanek, any idea why it fails on rhel8 with

yes, fails on recent openscap change

**Comment by mz-pdm** [comment]
Failed in the UI tests, the zero-copy migration looks OK.

**Comment by mz-pdm** [comment]
Rebased on master, I don't know if it helps with the failing tests.

**Comment by mz-pdm** [comment]
el8stream & rhel8 work, el9stream fails for an unrelated reason. Anything still needed to get this merged?

**Comment by michalskrivanek** [comment]
it would help if you describe what is that unrelated reason. why should anyone trust you, huh?:)

**Comment by michalskrivanek** [comment]
2022-09-30T11:38:15.055004+0000 ost-basic-suite-master-host-0 systemd[1]: Starting Virtual Desktop Server Manager...
2022-09-30T11:38:15.058454+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29457]: vdsm: Running mkdirs
2022-09-30T11:38:15.110928+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29457]: vdsm: Running configure_vdsm_logs
2022-09-30T11:38:15.115978+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29457]: vdsm: Running run_init_hooks
2022-09-30T11:38:15.216345+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29457]: vdsm: Running check_is_configured
2022-09-30T11:38:15.315535+0000 ost-basic-suite-master-host-0 SetroubleshootPrivileged.py[29446]: failed to retrieve rpm info for /var/lib/selinux/targeted/active/modules/400/openvswitch-custom
2022-09-30T11:38:15.364223+0000 ost-basic-suite-master-host-0 setroubleshoot[29368]: SELinux is preventing /usr/bin/kmod from search access on the directory events. For complete SELinux messages run: sealert -l 9b4fdac8-a660-4145-bbe9-c1df6652bd9f
2022-09-30T11:38:15.366798+0000 ost-basic-suite-master-host-0 setroubleshoot[29368]: SELinux is preventing /usr/bin/kmod from search access on the directory events.
                                                                                     
                                                                                     *****  Plugin catchall (100. confidence) suggests   **************************
                                                                                     
                                                                                     If you believe that kmod should be allowed search access on the events directory by default.
                                                                                     Then you should report this as a bug.
                                                                                     You can generate a local policy module to allow this access.
                                                                                     Do
                                                                                     allow this access for now by executing:
                                                                                     # ausearch -c 'modprobe' --raw | audit2allow -M my-modprobe
                                                                                     # semodule -X 300 -i my-modprobe.pp
                                                                                     
2022-09-30T11:38:15.367027+0000 ost-basic-suite-master-host-0 setroubleshoot[29368]: AnalyzeThread.run(): Set alarm timeout to 10
2022-09-30T11:38:15.367131+0000 ost-basic-suite-master-host-0 setroubleshoot[29368]: AnalyzeThread.run(): Cancel pending alarm
2022-09-30T11:38:15.535454+0000 ost-basic-suite-master-host-0 setroubleshoot[29368]: SELinux is preventing /usr/sbin/lldpad from sendto access on the unix_dgram_socket @/com/intel/lldpad/29291. For complete SELinux messages run: sealert -l 01366d69-39d7-4dfa-b719-0ebb42eb2ecc
2022-09-30T11:38:15.537033+0000 ost-basic-suite-master-host-0 setroubleshoot[29368]: SELinux is preventing /usr/sbin/lldpad from sendto access on the unix_dgram_socket @/com/intel/lldpad/29291.
                                                                                     
                                                                                     *****  Plugin catchall (100. confidence) suggests   **************************
                                                                                     
                                                                                     If you believe that lldpad should be allowed sendto access on the 29291 unix_dgram_socket by default.
                                                                                     Then you should report this as a bug.
                                                                                     You can generate a local policy module to allow this access.
                                                                                     Do
                                                                                     allow this access for now by executing:
                                                                                     # ausearch -c 'lldpad' --raw | audit2allow -M my-lldpad
                                                                                     # semodule -X 300 -i my-lldpad.pp
                                                                                     
2022-09-30T11:38:15.537299+0000 ost-basic-suite-master-host-0 setroubleshoot[29368]: AnalyzeThread.run(): Set alarm timeout to 10
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: Error:
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: One of the modules is not configured to work with VDSM.
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: To configure the module use the following:
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: 'vdsm-tool configure [--module module-name]'.
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: If all modules are not configured try to use:
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: 'vdsm-tool configure --force'
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: (The force flag will stop the module's service and start it
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: afterwards automatically to load the new configuration.)
2022-09-30T11:38:16.049404+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]:  
2022-09-30T11:38:16.049859+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: WARNING: LVM local configuration: /etc/lvm/lvmlocal.conf is not based on vdsm configuration
2022-09-30T11:38:16.049859+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: lvm requires configuration
2022-09-30T11:38:16.049859+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: Current revision of multipath.conf detected, preserving
2022-09-30T11:38:16.049859+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: libvirt is already configured for vdsm
2022-09-30T11:38:16.049859+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: Managed volume database is already configured
2022-09-30T11:38:16.049859+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: sanlock is configured for vdsm
2022-09-30T11:38:16.049859+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]: Modules lvm are not configured
2022-09-30T11:38:16.113079+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29479]:  
2022-09-30T11:38:16.113079+0000 ost-basic-suite-master-host-0 vdsmd_init_common.sh[29457]: vdsm: stopped during execute check_is_configured task (task returned with error code 1).
2022-09-30T11:38:16.113403+0000 ost-basic-suite-master-host-0 systemd[1]: vdsmd.service: Control process exited, code=exited, status=1/FAILURE
2022-09-30T11:38:16.113513+0000 ost-basic-suite-master-host-0 systemd[1]: vdsmd.service: Failed with result 'exit-code'.

**Comment by michalskrivanek** [comment]
@mz-pdm looks like it reliably fails. Why are you not running OST on PRs that were merged recently? Then it's hard to see what caused it...

**Comment by mz-pdm** [comment]
It fails now on the usual UI error on el9stream. If you're concerned about the Vdsm PR merged today that changed comments in files, it passes (minus the UI error) OST too, both el8stream and el9stream.

**Comment by michalskrivanek** [comment]
any idea about the startup error I quoted above?

**Review by michalskrivanek — APPROVED** [review]

**Comment by mz-pdm** [comment]
> any idea about the startup error I quoted above?

No. @aesteve-rh , @tinez , @nirs , do those error messages make sense to any of you?

**Comment by mz-pdm** [comment]
Ah, I see, that explains it, thanks.

**Pull request merged**
