### PR TITLE
Revert "basic: el8stream: Downgrade python on host-0 temporarily"

### PR DESCRIPTION
**Pull request by tinez**
Reverts oVirt/ovirt-system-tests#231

### CODE REVIEW

**Comment by nirs** [comment]
Do we have results from the weekend? If this eliminates the stuck vdsm issue,
it is better to run it for a week to be sure.

**Comment by tinez** [comment]
Unfortunately this didn't solve the issue - we still observe vdsm being stuck from time to time. We need to approach this problem from a different angle.

**Pull request merged**
