### PR TITLE
Revert "engine: Disable usage of keycloak (#120)"

### PR DESCRIPTION
**Pull request by arso**
This reverts commit eee65845afd3fd9af2933067c0d4076f1e3f438a.

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
Looks good, just not sure if this Friday is a good day to reenable it aagain

**Comment by arso** [comment]
> Looks good, just not sure if this Friday is a good day to reenable it aagain

Absolutely not! It's a draft and it should stay like that until I  have at least one green OST build. I would rather not merge it before Monday.

**Comment by michalskrivanek** [comment]
fwiw #133 is imho the right one to merge

**Comment by arso** [comment]
> 

Nah - only he related part  should be copied. That other patch is not intended to be merged because it hardcodes keycloak and installs keycloak packages which should be required as part of https://github.com/oVirt/ovirt-engine/pull/295. 

I would like to have basic suite passing first and then focus on HE part.

**Comment by arso** [comment]
Deprecated - closing

**Pull request closed without merging**
